// <auto-generated />
using System;
using EzEnglish.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzEnglish.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EzEnglishDbContext))]
    [Migration("20260611113822_SeedExpandedLessons")]
    partial class SeedExpandedLessons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameHe")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "/img/characters/lion.svg",
                            DisplayNameEn = "Leo the Lion",
                            DisplayNameHe = "ליאו האריה",
                            Key = "lion"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "/img/characters/bunny.svg",
                            DisplayNameEn = "Bella the Bunny",
                            DisplayNameHe = "בלה הארנבת",
                            Key = "bunny"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "/img/characters/owl.svg",
                            DisplayNameEn = "Ollie the Owl",
                            DisplayNameHe = "אולי הינשוף",
                            Key = "owl"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "/img/characters/robot.svg",
                            DisplayNameEn = "Rex the Robot",
                            DisplayNameHe = "רקס הרובוט",
                            Key = "robot"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ParentId");

                    b.ToTable("Children", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.ChildCategoryLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Category")
                        .IsUnique();

                    b.ToTable("ChildCategoryLevels", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OrderInLevel")
                        .HasColumnType("int");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleHe")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Level", "OrderInLevel");

                    b.ToTable("Lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "Colors — first three",
                            TitleHe = "צבעים — שלושת הראשונים"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Level = 1,
                            OrderInLevel = 2,
                            TitleEn = "Colors — listen and find",
                            TitleHe = "צבעים — הקשיבו ובחרו"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Level = 1,
                            OrderInLevel = 3,
                            TitleEn = "Colors — memory match",
                            TitleHe = "צבעים — משחק זיכרון"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "Farm friends",
                            TitleHe = "חברים מהחווה"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            Level = 1,
                            OrderInLevel = 2,
                            TitleEn = "Animals — listen and find",
                            TitleHe = "חיות — הקשיבו ובחרו"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Level = 1,
                            OrderInLevel = 3,
                            TitleEn = "Where do they live?",
                            TitleHe = "איפה הן גרות?"
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "My family",
                            TitleHe = "המשפחה שלי"
                        },
                        new
                        {
                            Id = 8,
                            Category = 3,
                            Level = 1,
                            OrderInLevel = 2,
                            TitleEn = "Family — listen and find",
                            TitleHe = "משפחה — הקשיבו ובחרו"
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Level = 1,
                            OrderInLevel = 3,
                            TitleEn = "Family memory",
                            TitleHe = "משפחה — משחק זיכרון"
                        },
                        new
                        {
                            Id = 10,
                            Category = 4,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "A, B, C — match it up",
                            TitleHe = "א, ב, ג — התאימו"
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            Level = 1,
                            OrderInLevel = 2,
                            TitleEn = "Find the letter",
                            TitleHe = "מצאו את האות"
                        },
                        new
                        {
                            Id = 12,
                            Category = 4,
                            Level = 1,
                            OrderInLevel = 3,
                            TitleEn = "Big and small letters",
                            TitleHe = "אותיות גדולות וקטנות"
                        },
                        new
                        {
                            Id = 13,
                            Category = 5,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "1, 2, 3 — count them",
                            TitleHe = "1, 2, 3 — סופרים"
                        },
                        new
                        {
                            Id = 14,
                            Category = 5,
                            Level = 1,
                            OrderInLevel = 2,
                            TitleEn = "Count and pick",
                            TitleHe = "סופרים ובוחרים"
                        },
                        new
                        {
                            Id = 15,
                            Category = 5,
                            Level = 1,
                            OrderInLevel = 3,
                            TitleEn = "Number memory",
                            TitleHe = "מספרים — משחק זיכרון"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.LessonItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderInLesson")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptEn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("PromptHe")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "OrderInLesson");

                    b.ToTable("LessonItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = 1,
                            LessonId = 1,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"/img/colors/red.svg\",\"label\":\"red\"},{\"image\":\"/img/colors/blue.svg\",\"label\":\"blue\"},{\"image\":\"/img/colors/yellow.svg\",\"label\":\"yellow\"}]}",
                            PromptEn = "Match the color to its name",
                            PromptHe = "התאימו את הצבע לשם שלו"
                        },
                        new
                        {
                            Id = 2,
                            Kind = 1,
                            LessonId = 1,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"/img/colors/green.svg\",\"label\":\"green\"},{\"image\":\"/img/colors/orange.svg\",\"label\":\"orange\"},{\"image\":\"/img/colors/purple.svg\",\"label\":\"purple\"}]}",
                            PromptEn = "Match the color to its name",
                            PromptHe = "התאימו את הצבע לשם שלו"
                        },
                        new
                        {
                            Id = 3,
                            Kind = 2,
                            LessonId = 2,
                            OrderInLesson = 1,
                            PayloadJson = "{\"correctLabel\":\"red\",\"choices\":[{\"image\":\"/img/colors/red.svg\",\"label\":\"red\"},{\"image\":\"/img/colors/blue.svg\",\"label\":\"blue\"},{\"image\":\"/img/colors/green.svg\",\"label\":\"green\"}]}",
                            PromptEn = "Tap the RED one",
                            PromptHe = "הקישו על האדום"
                        },
                        new
                        {
                            Id = 4,
                            Kind = 2,
                            LessonId = 2,
                            OrderInLesson = 2,
                            PayloadJson = "{\"correctLabel\":\"yellow\",\"choices\":[{\"image\":\"/img/colors/yellow.svg\",\"label\":\"yellow\"},{\"image\":\"/img/colors/orange.svg\",\"label\":\"orange\"},{\"image\":\"/img/colors/purple.svg\",\"label\":\"purple\"}]}",
                            PromptEn = "Tap the YELLOW one",
                            PromptHe = "הקישו על הצהוב"
                        },
                        new
                        {
                            Id = 5,
                            Kind = 2,
                            LessonId = 2,
                            OrderInLesson = 3,
                            PayloadJson = "{\"correctLabel\":\"blue\",\"choices\":[{\"image\":\"/img/colors/green.svg\",\"label\":\"green\"},{\"image\":\"/img/colors/blue.svg\",\"label\":\"blue\"},{\"image\":\"/img/colors/red.svg\",\"label\":\"red\"}]}",
                            PromptEn = "Tap the BLUE one",
                            PromptHe = "הקישו על הכחול"
                        },
                        new
                        {
                            Id = 6,
                            Kind = 4,
                            LessonId = 3,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"/img/colors/red.svg\",\"label\":\"red\"},{\"image\":\"/img/colors/blue.svg\",\"label\":\"blue\"},{\"image\":\"/img/colors/yellow.svg\",\"label\":\"yellow\"}]}",
                            PromptEn = "Find the matching colors",
                            PromptHe = "מצאו את הזוגות"
                        },
                        new
                        {
                            Id = 7,
                            Kind = 1,
                            LessonId = 4,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"🐱\",\"label\":\"cat\"},{\"image\":\"🐶\",\"label\":\"dog\"},{\"image\":\"🐮\",\"label\":\"cow\"}]}",
                            PromptEn = "Match the animal to its name",
                            PromptHe = "התאימו את החיה לשם שלה"
                        },
                        new
                        {
                            Id = 8,
                            Kind = 1,
                            LessonId = 4,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"🐷\",\"label\":\"pig\"},{\"image\":\"🐔\",\"label\":\"hen\"},{\"image\":\"🐑\",\"label\":\"sheep\"}]}",
                            PromptEn = "Match the animal to its name",
                            PromptHe = "התאימו את החיה לשם שלה"
                        },
                        new
                        {
                            Id = 9,
                            Kind = 2,
                            LessonId = 5,
                            OrderInLesson = 1,
                            PayloadJson = "{\"correctLabel\":\"cat\",\"choices\":[{\"image\":\"🐱\",\"label\":\"cat\"},{\"image\":\"🐶\",\"label\":\"dog\"},{\"image\":\"🐰\",\"label\":\"rabbit\"}]}",
                            PromptEn = "Find the CAT",
                            PromptHe = "מצאו את החתול"
                        },
                        new
                        {
                            Id = 10,
                            Kind = 2,
                            LessonId = 5,
                            OrderInLesson = 2,
                            PayloadJson = "{\"correctLabel\":\"lion\",\"choices\":[{\"image\":\"🐯\",\"label\":\"tiger\"},{\"image\":\"🦁\",\"label\":\"lion\"},{\"image\":\"🐻\",\"label\":\"bear\"}]}",
                            PromptEn = "Find the LION",
                            PromptHe = "מצאו את האריה"
                        },
                        new
                        {
                            Id = 11,
                            Kind = 2,
                            LessonId = 5,
                            OrderInLesson = 3,
                            PayloadJson = "{\"correctLabel\":\"elephant\",\"choices\":[{\"image\":\"🦒\",\"label\":\"giraffe\"},{\"image\":\"🐵\",\"label\":\"monkey\"},{\"image\":\"🐘\",\"label\":\"elephant\"}]}",
                            PromptEn = "Find the ELEPHANT",
                            PromptHe = "מצאו את הפיל"
                        },
                        new
                        {
                            Id = 12,
                            Kind = 5,
                            LessonId = 6,
                            OrderInLesson = 1,
                            PayloadJson = "{\"bins\":[{\"id\":\"farm\",\"label\":\"Farm\",\"emoji\":\"🚜\"},{\"id\":\"wild\",\"label\":\"Wild\",\"emoji\":\"🌳\"}],\"items\":[{\"image\":\"🐮\",\"label\":\"cow\",\"binId\":\"farm\"},{\"image\":\"🐷\",\"label\":\"pig\",\"binId\":\"farm\"},{\"image\":\"🐔\",\"label\":\"hen\",\"binId\":\"farm\"},{\"image\":\"🦁\",\"label\":\"lion\",\"binId\":\"wild\"},{\"image\":\"🐯\",\"label\":\"tiger\",\"binId\":\"wild\"},{\"image\":\"🐘\",\"label\":\"elephant\",\"binId\":\"wild\"}]}",
                            PromptEn = "Drag each animal to its home",
                            PromptHe = "גררו כל חיה לבית שלה"
                        },
                        new
                        {
                            Id = 13,
                            Kind = 1,
                            LessonId = 7,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"👩\",\"label\":\"mom\"},{\"image\":\"👨\",\"label\":\"dad\"},{\"image\":\"👶\",\"label\":\"baby\"}]}",
                            PromptEn = "Match family members to names",
                            PromptHe = "התאימו את בני המשפחה לשמות"
                        },
                        new
                        {
                            Id = 14,
                            Kind = 1,
                            LessonId = 7,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"👦\",\"label\":\"brother\"},{\"image\":\"👧\",\"label\":\"sister\"},{\"image\":\"👵\",\"label\":\"grandma\"}]}",
                            PromptEn = "Match family members to names",
                            PromptHe = "התאימו את בני המשפחה לשמות"
                        },
                        new
                        {
                            Id = 15,
                            Kind = 2,
                            LessonId = 8,
                            OrderInLesson = 1,
                            PayloadJson = "{\"correctLabel\":\"mom\",\"choices\":[{\"image\":\"👨\",\"label\":\"dad\"},{\"image\":\"👩\",\"label\":\"mom\"},{\"image\":\"👵\",\"label\":\"grandma\"}]}",
                            PromptEn = "Find MOM",
                            PromptHe = "מצאו את אמא"
                        },
                        new
                        {
                            Id = 16,
                            Kind = 2,
                            LessonId = 8,
                            OrderInLesson = 2,
                            PayloadJson = "{\"correctLabel\":\"baby\",\"choices\":[{\"image\":\"👦\",\"label\":\"brother\"},{\"image\":\"👧\",\"label\":\"sister\"},{\"image\":\"👶\",\"label\":\"baby\"}]}",
                            PromptEn = "Find BABY",
                            PromptHe = "מצאו את התינוק/ת"
                        },
                        new
                        {
                            Id = 17,
                            Kind = 2,
                            LessonId = 8,
                            OrderInLesson = 3,
                            PayloadJson = "{\"correctLabel\":\"grandpa\",\"choices\":[{\"image\":\"👴\",\"label\":\"grandpa\"},{\"image\":\"👵\",\"label\":\"grandma\"},{\"image\":\"👨\",\"label\":\"dad\"}]}",
                            PromptEn = "Find GRANDPA",
                            PromptHe = "מצאו את סבא"
                        },
                        new
                        {
                            Id = 18,
                            Kind = 4,
                            LessonId = 9,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"👩\",\"label\":\"mom\"},{\"image\":\"👨\",\"label\":\"dad\"},{\"image\":\"👶\",\"label\":\"baby\"}]}",
                            PromptEn = "Find the matching family members",
                            PromptHe = "מצאו את הזוגות"
                        },
                        new
                        {
                            Id = 19,
                            Kind = 1,
                            LessonId = 10,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"🍎\",\"label\":\"A\"},{\"image\":\"⚽\",\"label\":\"B\"},{\"image\":\"🐱\",\"label\":\"C\"}]}",
                            PromptEn = "Match each thing to its first letter",
                            PromptHe = "התאימו כל דבר לאות הראשונה שלו"
                        },
                        new
                        {
                            Id = 20,
                            Kind = 1,
                            LessonId = 10,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"🐶\",\"label\":\"D\"},{\"image\":\"🥚\",\"label\":\"E\"},{\"image\":\"🐟\",\"label\":\"F\"}]}",
                            PromptEn = "Match each thing to its first letter",
                            PromptHe = "התאימו כל דבר לאות הראשונה שלו"
                        },
                        new
                        {
                            Id = 21,
                            Kind = 2,
                            LessonId = 11,
                            OrderInLesson = 1,
                            PayloadJson = "{\"correctLabel\":\"A\",\"choices\":[{\"image\":\"A\",\"label\":\"A\"},{\"image\":\"E\",\"label\":\"E\"},{\"image\":\"O\",\"label\":\"O\"}]}",
                            PromptEn = "Tap the letter A",
                            PromptHe = "הקישו על האות A"
                        },
                        new
                        {
                            Id = 22,
                            Kind = 2,
                            LessonId = 11,
                            OrderInLesson = 2,
                            PayloadJson = "{\"correctLabel\":\"B\",\"choices\":[{\"image\":\"D\",\"label\":\"D\"},{\"image\":\"B\",\"label\":\"B\"},{\"image\":\"P\",\"label\":\"P\"}]}",
                            PromptEn = "Tap the letter B",
                            PromptHe = "הקישו על האות B"
                        },
                        new
                        {
                            Id = 23,
                            Kind = 2,
                            LessonId = 11,
                            OrderInLesson = 3,
                            PayloadJson = "{\"correctLabel\":\"S\",\"choices\":[{\"image\":\"S\",\"label\":\"S\"},{\"image\":\"Z\",\"label\":\"Z\"},{\"image\":\"X\",\"label\":\"X\"}]}",
                            PromptEn = "Tap the letter S",
                            PromptHe = "הקישו על האות S"
                        },
                        new
                        {
                            Id = 24,
                            Kind = 4,
                            LessonId = 12,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"A\",\"label\":\"a\"},{\"image\":\"B\",\"label\":\"b\"},{\"image\":\"C\",\"label\":\"c\"}]}",
                            PromptEn = "Match each big letter with its small letter",
                            PromptHe = "התאימו כל אות גדולה לאות הקטנה"
                        },
                        new
                        {
                            Id = 25,
                            Kind = 1,
                            LessonId = 13,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"🍎\",\"label\":\"1\"},{\"image\":\"🍎🍎\",\"label\":\"2\"},{\"image\":\"🍎🍎🍎\",\"label\":\"3\"}]}",
                            PromptEn = "Match the picture to the number",
                            PromptHe = "התאימו את התמונה למספר"
                        },
                        new
                        {
                            Id = 26,
                            Kind = 1,
                            LessonId = 13,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"⭐⭐⭐⭐\",\"label\":\"4\"},{\"image\":\"⭐⭐⭐⭐⭐\",\"label\":\"5\"},{\"image\":\"⭐⭐⭐⭐⭐⭐\",\"label\":\"6\"}]}",
                            PromptEn = "Match the picture to the number",
                            PromptHe = "התאימו את התמונה למספר"
                        },
                        new
                        {
                            Id = 27,
                            Kind = 2,
                            LessonId = 14,
                            OrderInLesson = 1,
                            PayloadJson = "{\"correctLabel\":\"3\",\"choices\":[{\"image\":\"1\",\"label\":\"1\"},{\"image\":\"3\",\"label\":\"3\"},{\"image\":\"5\",\"label\":\"5\"}]}",
                            PromptEn = "How many apples? Tap the number.",
                            PromptHe = "כמה תפוחים? הקישו על המספר."
                        },
                        new
                        {
                            Id = 28,
                            Kind = 2,
                            LessonId = 14,
                            OrderInLesson = 2,
                            PayloadJson = "{\"correctLabel\":\"2\",\"choices\":[{\"image\":\"4\",\"label\":\"4\"},{\"image\":\"2\",\"label\":\"2\"},{\"image\":\"7\",\"label\":\"7\"}]}",
                            PromptEn = "Tap the number TWO",
                            PromptHe = "הקישו על המספר שתיים"
                        },
                        new
                        {
                            Id = 29,
                            Kind = 2,
                            LessonId = 14,
                            OrderInLesson = 3,
                            PayloadJson = "{\"correctLabel\":\"5\",\"choices\":[{\"image\":\"3\",\"label\":\"3\"},{\"image\":\"8\",\"label\":\"8\"},{\"image\":\"5\",\"label\":\"5\"}]}",
                            PromptEn = "Tap the number FIVE",
                            PromptHe = "הקישו על המספר חמש"
                        },
                        new
                        {
                            Id = 30,
                            Kind = 4,
                            LessonId = 15,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"1\",\"label\":\"one\"},{\"image\":\"2\",\"label\":\"two\"},{\"image\":\"3\",\"label\":\"three\"}]}",
                            PromptEn = "Match each number to its name",
                            PromptHe = "התאימו כל מספר לשם שלו"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonItemId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonItemId");

                    b.HasIndex("ChildId", "LessonItemId")
                        .IsUnique();

                    b.ToTable("Progress", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EzEnglish.Api.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.ChildCategoryLevel", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Child", "Child")
                        .WithMany("CategoryLevels")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.LessonItem", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Items")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Progress", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Child", "Child")
                        .WithMany("Progress")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EzEnglish.Api.Domain.Entities.LessonItem", "LessonItem")
                        .WithMany()
                        .HasForeignKey("LessonItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("LessonItem");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.Navigation("CategoryLevels");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
