// <auto-generated />
using System;
using EzEnglish.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzEnglish.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EzEnglishDbContext))]
    [Migration("20260611093309_SeedColorsLesson")]
    partial class SeedColorsLesson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameHe")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "/img/characters/lion.svg",
                            DisplayNameEn = "Leo the Lion",
                            DisplayNameHe = "ליאו האריה",
                            Key = "lion"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "/img/characters/bunny.svg",
                            DisplayNameEn = "Bella the Bunny",
                            DisplayNameHe = "בלה הארנבת",
                            Key = "bunny"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "/img/characters/owl.svg",
                            DisplayNameEn = "Ollie the Owl",
                            DisplayNameHe = "אולי הינשוף",
                            Key = "owl"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "/img/characters/robot.svg",
                            DisplayNameEn = "Rex the Robot",
                            DisplayNameHe = "רקס הרובוט",
                            Key = "robot"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ParentId");

                    b.ToTable("Children", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.ChildCategoryLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Category")
                        .IsUnique();

                    b.ToTable("ChildCategoryLevels", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OrderInLevel")
                        .HasColumnType("int");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleHe")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Level", "OrderInLevel");

                    b.ToTable("Lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Level = 1,
                            OrderInLevel = 1,
                            TitleEn = "Colors — first three",
                            TitleHe = "צבעים — שלושת הראשונים"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.LessonItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderInLesson")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptEn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("PromptHe")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "OrderInLesson");

                    b.ToTable("LessonItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = 1,
                            LessonId = 1,
                            OrderInLesson = 1,
                            PayloadJson = "{\"pairs\":[{\"image\":\"/img/colors/red.svg\",\"label\":\"red\"},{\"image\":\"/img/colors/blue.svg\",\"label\":\"blue\"},{\"image\":\"/img/colors/yellow.svg\",\"label\":\"yellow\"}]}",
                            PromptEn = "Match the color to its name",
                            PromptHe = "התאימו את הצבע לשם שלו"
                        },
                        new
                        {
                            Id = 2,
                            Kind = 1,
                            LessonId = 1,
                            OrderInLesson = 2,
                            PayloadJson = "{\"pairs\":[{\"image\":\"/img/colors/green.svg\",\"label\":\"green\"},{\"image\":\"/img/colors/orange.svg\",\"label\":\"orange\"},{\"image\":\"/img/colors/purple.svg\",\"label\":\"purple\"}]}",
                            PromptEn = "Match the color to its name",
                            PromptHe = "התאימו את הצבע לשם שלו"
                        });
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonItemId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonItemId");

                    b.HasIndex("ChildId", "LessonItemId")
                        .IsUnique();

                    b.ToTable("Progress", (string)null);
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EzEnglish.Api.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.ChildCategoryLevel", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Child", "Child")
                        .WithMany("CategoryLevels")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.LessonItem", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Items")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Progress", b =>
                {
                    b.HasOne("EzEnglish.Api.Domain.Entities.Child", "Child")
                        .WithMany("Progress")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EzEnglish.Api.Domain.Entities.LessonItem", "LessonItem")
                        .WithMany()
                        .HasForeignKey("LessonItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("LessonItem");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Child", b =>
                {
                    b.Navigation("CategoryLevels");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EzEnglish.Api.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
